<?php

function cipher_menu() {
  $items['cipher'] = array (
  'title' => 'Cipher',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('cipher_form'),
  'access callback' => TRUE,
  'type' = MENU_NORMAL_ITEM,
  );

  $items['success'] = array(
    'title' => 'Done',
    'page callback' => 'cipher_done',
    'access callback' => TRUE,
    'type' = MENU_CALLBACK,
  );

  return $items;
}
