<?php

function cipher_menu() {
  $items['cipher'] = array (
  'title' => 'Cipher',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('cipher_form'),
  'access callback' => TRUE,
  'type' = MENU_NORMAL_ITEM,
  );

  $items['success'] = array(
    'title' => 'Done',
    'page callback' => 'cipher_done',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function cipher_form() {
  $form['shift_value'] = array(
    '#title' => 'Shift value',
    '#type' => 'textfield',
    '#description' => t('Enter the number of letters you would like the cipher to shift'),
    '#element_validate' => array('element_validate_integer_positive'),
    '#required' => TRUE,
  );

  $form['shift_direction'] = array(
    '#title' => 'Shift direction',
    '#type' => 'select',
    '#description' => t('Select which direction the cipher will move in the alphabet'),
    '#options' => array(
      'left' => t('Left'),
      'right' => t('Right'),
    ),
    '#required' => TRUE,
  );

  $form['phrase'] = array(
    '#title' => 'Phrase',
    '#type' => 'textfield',
    '#description' => t('Enter the phrase you would like to cipher'),
    '#element_validate' => array('element_validate_input_range'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
  );

  return $form;
}
//
// function element_validate_input_range($element) {
//   if($element[''])
// }
